spring.application.name=demo
server.port=${PORT:8080}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.level.org.flywaydb=DEBUG

server.servlet.context-path=/api

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

whatsapp.api.url=https://graph.facebook.com/v25.0
whatsapp.phone.number.id=${WHATSAPP_PHONE_NUMBER_ID}
whatsapp.access.token=${WHATSAPP_ACCESS_TOKEN}