CREATE TABLE problem_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    icon VARCHAR(255),
    admin_id BIGINT NOT NULL,
    CONSTRAINT fk_problem_types_admin FOREIGN KEY (admin_id) REFERENCES users (id)
);
